
export const sectionFooterNotesDummy_Home = [
    <>
        1. Qualified Purchasers receive an Apple Gift Card when they purchase an eligible Mac or iPad at a Qualifying Location. Only one Apple Gift Card per eligible Mac or iPad per Qualified Purchaser. Offer subject to availability. While supplies last. Qualified Purchasers shall receive a discount equal to the value of the Apple Gift Card off the price of the eligible Mac or iPad, but will be charged for all items in their cart, including the Apple Gift Card. Important notice regarding the checkout receipt and monthly statement for Apple Card Monthly Installment (ACMI) purchases with this promotion: Qualified Purchasers selecting ACMI (a 0% APR payment option) as payment type at checkout shall receive a discount equal to the value of the Apple Gift Card off the price of the eligible Mac or iPad. This will result in one ACMI installment plan over 12 months for the eligible iPad or Mac discounted by the instant credit, and a second ACMI installment plan over 12 months for the full price of the Apple Gift Card. The total combined amount charged over the two separate ACMI installment plans will reflect the original full retail price of the Eligible Product. Separately, Qualified Purchasers will receive and be charged for the Apple Gift Card in the amount of the applicable discount off the eligible Mac or iPad. ACMI is subject to credit approval and credit limit. Variable APRs for Apple Card other than ACMI range from 12.49% to 23.49% based on creditworthiness. Rates as of July 1, 2022. If you choose the pay‑in‑full or one‑time‑payment option for an ACMI‑eligible purchase instead of choosing ACMI as the payment option at checkout, that purchase will be subject to the variable APR assigned to your Apple Card. Taxes and shipping are not included in ACMI transactions and are subject to your standard purchase APR. See the Apple Card Customer Agreement at for more information. ACMI is not available for purchases made online at the following special stores: Apple Employee Purchase Plan; participating corporate Employee Purchase Programs; Apple at Work for small businesses; Government, and Veterans and Military Purchase Programs, or on refurbished devices. Apple Card is issued by Goldman Sachs Bank USA, Salt Lake City Branch. Available for qualifying applicants in the United States. If you reside in the U.S. territories, please call Goldman Sachs at 877-255-5923 with questions about accessing this offer or applying for Apple Card. This offer cannot be combined with the Apple Employee Purchase Plan or business loyalty pricing. Availability of in‑store promotion offerings may be limited by Apple Store location closures as a result of COVID‑19. Additional restrictions apply. View full terms and conditions of offer <a href="https://www.goldmansachs.com/terms-and-conditions/Apple-Card-Customer-Agreement.pdf">here</a>
    </>,
    'To access and use all the features of Apple Card, you must add Apple Card to Wallet on an iPhone or iPad with the latest version of iOS or iPadOS. Update to the latest version by going to Settings  >  General  >  Software Update. Tap Download and Install.',
    'Available for qualifying applicants in the United States.',
    'Apple Card is issued by Goldman Sachs Bank USA, Salt Lake City Branch.',
    <>Learn more about how Apple Card applications are evaluated at <a href="https://support.apple.com/kb/HT209218">support.apple.com/kb/HT209218</a>.</>,
    'Major League Baseball trademarks and copyrights are used with permission of MLB Advanced Media, L.P. All rights reserved.'
]

export const sectionFooterNotesDummy_Iphone13 = [
    '* Price includes a $30 AT&T, T-Mobile, Sprint, or Verizon discount. Requires activation with carrier.',
    '** AT&T Special Deal: Offer pricing will reflect application of AT&T trade‑in credit applied over 36 months after trade‑in of eligible smartphone. Requires upgrade of an existing line or activation of a new line and purchase of a new iPhone 13 mini, iPhone 13, iPhone 13 Pro, or iPhone 13 Pro Max on qualifying 36‑month 0% APR installment plan, subject to carrier credit qualification. AT&T Installment Plan with Next Up is not eligible for this promotion. $0 down for well‑qualified customers only, or down payment may be required and depends on a variety of factors. Tax on full retail price due at sale. Requires activation on eligible unlimited plan. If you cancel eligible wireless service, credits will stop and you will owe the remaining device balance. Activation/Upgrade Fee: $30. Trade‑in device may not be on existing installment plan. Bill credits are applied as a monthly credit over the 36‑month installment plan. Credits start within 3 bills. Will receive catch‑up credits once credits start. Wireless line must be on an installment agreement, active, and in good standing for 30 days to qualify. Installment agreement starts when device is shipped. To get all credits, device must remain on agreement for entire term and you must keep eligible service on device for entire installment term. Limited‑time offer; subject to change. Limits: one trade‑in per qualifying purchase and one credit per line. May not be combinable with other offers, discounts, or credits. Purchase, financing, other limits, and restrictions apply. Price for iPhone 13 and iPhone 13 mini includes $30 AT&T instant discount. Activation required.',
    'Sprint Special Deal: Sprint trade‑in credit in the form of a rebate with virtual prepaid card when you trade in a qualifying device. Limited‑time offer; subject to change. Requires activation on any Sprint data plan and submission of a promo code at promotions.t‑mobile.com. $200 rebate via virtual prepaid Mastercard® Card, which you can use online or in‑store via accepted mobile payment apps; no cash access & expires in 6 months from issuance. Card is issued by Sunrise Banks N.A., Member FDIC, pursuant to a license from Mastercard International Incorporated. Mastercard is a registered trademark of Mastercard International Incorporated. Use of this card constitutes acceptance of the terms and conditions stated in the Cardholder Agreement. Lines must be active and in good standing when card is issued. Allow up to 2 billing cycles after fulfillment of offer requirements. Max 4 per account offer/discounted devices/account. May not be combined with some offers or discounts. Sales tax may be assessed on full value of new iPhone. Requires trade‑in of an iPhone XR or newer in good condition, excluding iPhone SE (2nd generation). Must be at least 18 to trade in. Apple or its trade‑in partners reserve the right to refuse or limit any trade‑in transaction for any reason. In‑store trade‑in requires presentation of a valid, government‑issued photo ID (local law may require saving this information). In‑store promotion availability subject to local law; speak to a Specialist to learn more. Additional terms from Apple, Sprint, and Apple’s trade‑in partners may apply.',
    'T-Mobile Special Deal: Offer pricing will reflect savings up to $400 (w/ trade‑in of iPhone X or newer), $200 (w/ trade‑in of iPhone 8/8+, iPhone 7/7+, iPhone SE 2nd Gen) or $100 (iPhone 6/6+, iPhone 6s/6s+) with purchase and T‑Mobile financing of qualifying iPhone and choice of eligible data plan. Savings comprised of (i) Apple instant trade‑in credit at checkout and (ii) T‑Mobile monthly bill credits applied over 24 months. Customer must remain in the T‑Mobile Equipment Installment Program and on eligible data plan for 24 months and remain in good standing to receive the full benefit of the bill credits; allow 2 bill cycles from valid submission and validation of trade in. Tax on pre‑credit price due at sale. Limited‑time offer; subject to change. Qualifying credit, data plan, and trade‑in in good condition required. Max 4/account. May not be combinable with some offers or discounts. Price for iPhone 13, iPhone 13 mini, iPhone 12, and iPhone 12 mini includes $30 T‑Mobile instant discount. Activation required.',
    'Verizon Special Deal: Offer pricing will reflect application of Verizon’s trade‑in credit up to $440 (iPhone 13, iPhone 13 Pro, iPhone 13 Pro Max) or $412 (iPhone 13 mini) after trade‑in of eligible smartphone. Savings comprised of (i) Apple instant trade‑in credit at checkout and (ii) Verizon monthly bill credits applied over 36 months. Customer must remain in the Verizon Device Payment Program for 36 months to receive the full benefit of the Verizon bill credits. Bill credits may take 1‑2 bill cycles to appear. If it takes two cycles for bill credits to appear, you’ll see the credit for the first cycle on your second bill in addition to that month’s credit. Requires purchase and activation of a new iPhone 13 mini, iPhone 13, iPhone 13 Pro, or iPhone 13 Pro Max with the Verizon Device Payment Program at 0% APR for 36 months, subject to carrier credit qualification, and iPhone availability and limits. Taxes and shipping not included in monthly price. Sales tax may be assessed on full value of new iPhone. Requires eligible unlimited service plan. Requires trade‑in of eligible device in eligible condition. Must be at least 18 to trade‑in. Apple or its trade‑in partners reserve the right to refuse or limit any trade‑in transaction for any reason. In‑store trade‑in requires presentation of a valid, government‑issued photo ID (local law may require saving this information). In‑store promotion availability subject to local law; speak to a Specialist to learn more. Limited‑time offer; subject to change. Additional terms from Apple, Verizon, and Apple’s trade‑in partners may apply. Price for iPhone 13 mini, and iPhone 13 includes $30 Verizon instant discount. Activation required.',
    <ol>
        <li>Available to qualified customers and requires 24‑month installment loan when you select Citizens One or Apple Card Monthly Installments (ACMI) as payment type at checkout at Apple. iPhone activation required with AT&T, T‑Mobile, Sprint, or Verizon for purchases made with ACMI at an Apple Store. Subject to credit approval and credit limit. Taxes and shipping are not included in ACMI and are subject to your card’s variable APR. Additional Apple Card Monthly Installments terms are in the Customer Agreement. Additional iPhone Payments terms are here. ACMI is not available for purchases made online at special storefronts. The last month’s payment for each product will be the product’s purchase price, less all other payments at the monthly payment amount.</li>
        <li>All battery claims depend on network configuration and many other factors; actual results will vary. Battery has limited recharge cycles and may eventually need to be replaced by Apple service provider. Battery life and charge cycles vary by use and settings. See apple.com/batteries and apple.com/iphone/battery.html for more information.</li>
        <li>iPhone 13 and iPhone 13 mini are splash, water, and dust resistant and were tested under controlled laboratory conditions with a rating of IP68 under IEC standard 60529 (maximum depth of 6 meters up to 30 minutes). Splash, water, and dust resistance are not permanent conditions.</li>
        <li>Resistance might decrease as a result of normal wear. Do not attempt to charge a wet iPhone; refer to the user guide for cleaning and drying instructions. Liquid damage not covered under warranty.</li>
        <li>Data plan required. 5G and LTE are available in select markets and through select carriers. Speeds vary by site conditions and carrier. For details on 5G and LTE support, contact your carrier and see apple.com/iphone/cellular.</li>
        <li>The display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 5.42 inches (iPhone 13 mini), 6.06 inches (iPhone 13, iPhone 13 Pro), 6.68 inches (iPhone 13 Pro Max), 5.42 inches (iPhone 12 mini), or 6.06 inches (iPhone 12, iPhone 11) diagonally. Actual viewable area is less.</li>
        <li>Trade‑in values will vary based on the condition, year, and configuration of your eligible trade‑in device. Not all devices are eligible for credit. You must be at least 18 years old to be eligible to trade in for credit or for an Apple Gift Card. Trade‑in value may be applied toward qualifying new device purchase, or added to an Apple Gift Card. Actual value awarded is based on receipt of a qualifying device matching the description provided when estimate was made. Sales tax may be assessed on full value of a new device purchase. In‑store trade‑in requires presentation of a valid photo ID (local law may require saving this information). Offer may not be available in all stores, and may vary between in‑store and online trade‑in. Some stores may have additional requirements. Apple or its trade‑in partners reserve the right to refuse or limit quantity of any trade‑in transaction for any reason. More details are available from Apple’s trade‑in partner for trade‑in and recycling of eligible devices. Restrictions and limitations may apply.</li>
        <li>Program available for iPhone 13 and iPhone 13 Pro. Available to qualified customers with a credit check and eligible U.S. credit or debit card. Requires a 24-month installment loan with a 0% APR from Citizens Bank, N.A. (subject to any interest, fees, or other costs payable to the card issuer), purchase of AppleCare+ for iPhone, and iPhone activation with one of these national carriers: AT&T, Sprint, Verizon, or T-Mobile. Sales tax and any applicable fees due at time of purchase. Full terms apply.</li>
    </ol>,
    '† Apple Card Monthly Installments (ACMI) is a 0% APR payment option available only in the U.S. to select at checkout for certain Apple products purchased at Apple Store locations, apple.com, the Apple Store app, or by calling 1-800-MY-APPLE and is subject to credit approval and credit limit. See support.apple.com/kb/HT211204 for more information about eligible products. Variable APRs for Apple Card other than ACMI range from 12.49% to 23.49% based on creditworthiness. Rates as of July 1, 2022. If you choose the pay‑in‑full or one‑time‑payment option for an ACMI‑eligible purchase instead of choosing ACMI as the payment option at checkout, that purchase will be subject to the variable APR assigned to your Apple Card. Taxes and shipping are not included in ACMI and are subject to your card’s variable APR. See the Apple Card Customer Agreement for more information. ACMI is not available for purchases made online at the following special stores: Apple Employee Purchase Plan; participating corporate Employee Purchase Programs; Apple at Work for small businesses; Government, and Veterans and Military Purchase Programs, or on refurbished devices. iPhone activation required on iPhone purchases made at an Apple Store with one of these national carriers: AT&T;, Sprint, Verizon, or T‑Mobile.',
    'To access and use all the features of Apple Card, you must add Apple Card to Wallet on an iPhone or iPad with the latest version of iOS or iPadOS. Update to the latest version by going to Settings > General > Software Update. Tap Download and Install.',
    'Available for qualifying applicants in the United States.',
    'Apple Card is issued by Goldman Sachs Bank USA, Salt Lake City Branch.',
    'If you reside in the U.S. territories, please call Goldman Sachs at 877‑255‑5923 with questions about Apple Card.'
]